# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='creator',
        ),
        migrations.AddField(
            model_name='trip',
            name='planner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planned_trips', to='travel_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='trip',
            field=models.ManyToManyField(related_name='attendees', to='travel_app.Trip'),
        ),
    ]
